version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"

